### ISSUE TITLE
`FixedCapacityDequeLike::clone()` can cause dropping uninitialized memory

### ISSUE THREAD

**Issue by JOE1994** [L117/array-tools#2]
Hello 🦀 ,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description
https://github.com/L117/array-tools/blob/170f922f4010ffabd97bec552e05f74088cce93f/src/lib.rs#L215-L236

https://github.com/L117/array-tools/blob/170f922f4010ffabd97bec552e05f74088cce93f/src/lib.rs#L169-L178

If the `src.clone()` (user supplied `T::clone()`) panics within `FixedCapacityDequeLike::clone()`,
then `FixedCapacityDequeLike` with its **uninitialized** `self.array` is dropped.
The `Drop` impl of `FixedCapacityDequeLike` assumes that `self.array` is a properly initialized array,
and thus `drop()` can be invoked on an uninitialized memory blob.

Thank you for checking out this issue :+1:

**Comment by Shnatsel** [comment]
Heads up: this issue has been included in the [RustSec advisory database](https://github.com/RustSec/advisory-db). It will be surfaced by tools such as [cargo-audit](https://github.com/RustSec/cargo-audit) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny) from now on.

Once a fix is released to crates.io, please open a pull request to update the advisory with the patched version, or file an issue on [the advisory database repository](https://github.com/RustSec/advisory-db).

**Comment by L117** [comment]
Resolved in https://github.com/L117/array-tools/commit/709d89f23c5b2e81ed25537446f838c3cdb73b6f
